#-------------------------------------------
# This script sets out to load all 
# things required for the project
#
# NOTE: This script requires setup.R to
# have been run first
#-------------------------------------------

#-------------------------------------------
# Author: Trent Henderson, 17 September 2020
#-------------------------------------------

# Prep data

prep <- the_data %>%
  mutate(plays_c = (log(plays) - mean(log(plays)))/sd(log(plays)),
         likes_c = (log(fb_likes) - mean(log(fb_likes)))/sd(log(fb_likes)),
         days_c = (days_released - mean(days_released))/sd(days_released),
         rank_c = (the_rank - mean(the_rank))/sd(the_rank))

#------------------------- MODEL SPECIFICATION ---------------------

m1 <- prep[1:nrow(prep), ] %>%
  dplyr::select(plays_c, likes_c, days_c, rank_c) %>%
  single_imputation() %>%
  estimate_profiles(1:4,
                    variances = c("equal", "varying"),
                    covariances = c("zero", "varying"))

#------------------------- OUTPUTS ---------------------------------

#-----------------
# FIT INDICES
#-----------------

m1 %>%
  compare_solutions(statistics = c("AIC", "BIC", "AWE", "CLC", "KIC"))

#-----------------
# DEFAULT LPA PLOT
#-----------------

m1 %>%
  plot_profiles()

#-----------------
# COLLECT OUTPUTS
#-----------------

# Get outputs in a dataframe

lpa_outputs <- get_data(m1)

# Filter to just Model 1/Classes 3 as this has the best analytical hierarchy scores

lpa_outputs_filt <- lpa_outputs %>%
  filter(model_number == "1" & classes_number == 3)

# Join back in to main dataset

with_outs <- prep %>%
  inner_join(lpa_outputs_filt, by = c("plays_c" = "plays_c", "likes_c" = "likes_c", 
                                      "days_c" = "days_c", "rank_c" = "rank_c")) %>%
  group_by(song) %>%
  slice(which.max(Probability)) %>%
  ungroup() %>%
  mutate(Class = as.factor(Class))

#------------------------- PLOTS -----------------------------------

# Box & whisker

p <- with_outs %>%
  gather(key = metric, value = value, 10:13) %>%
  mutate(metric = case_when(
         metric == "days_c" ~ "Days Since Song Release",
         metric == "likes_c" ~ "Artist Facebook Likes",
         metric == "plays_c" ~ "Song Spotify Plays",
         metric == "rank_c" ~ "Hottest 100 Rank")) %>%
  ggplot(aes(x = Class, y = value)) +
  geom_boxplot(aes(colour = Class)) +
  geom_point(aes(colour = Class), alpha = 0.7, size = 1.5) +
  labs(title = "Distribution of metrics used in Hottest 100 algorithm split by class",
       subtitle = "Classes generated by Latent Profile Analysis",
       x = "Class",
       y = "Value (Centred and Standardised)",
       caption = "Analysis: Orbisant Analytics.") +
  scale_colour_manual(values = c("#189AB4", "#FD62AD", "#FEB06A")) +
  theme_bw() +
  theme(legend.position = "bottom",
        panel.grid.minor = element_blank(),
        strip.background = element_rect(fill = "#05445E"),
        strip.text = element_text(colour = "white", face = "bold")) +
  facet_wrap(~metric)
print(p)

# Export

CairoPNG("output/boxplot.png", 800, 600)
print(p)
dev.off()
